In [156]:
# Cálculo científico y vectorial para python
import numpy as np
# Libreria para graficos
from matplotlib import pyplot
# Modulo de optimizacion en scipy
from scipy import optimize
# modulo para cargar archivos en formato MATLAB
from scipy.io import loadmat
import pandas as pd

In [157]:
# cargar a una variable el dataset
# https://www.kaggle.com/datasets/whenamancodes/alcohol-effects-on-study
data = pd.read_csv("maths_pre.csv")
data
# sex,age,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3


2  18  4  4.1  2.1  2.2  0  1  0.1  0.2  ...  4.2  3  4.3  1.3  1.4  3.1   
0    2  17  1    1    1    2  0  0    1    0  ...    5  3    3    1    1    3  \
1    2  15  1    1    1    2  3  1    0    1  ...    4  3    2    2    3    3   
2    2  15  4    2    1    3  0  0    1    1  ...    3  2    2    1    1    5   
3    2  16  3    3    1    2  0  0    1    1  ...    4  3    2    1    2    5   
4    1  16  4    3    1    2  0  0    1    1  ...    5  4    2    1    2    5   
..  ..  .. ..  ...  ...  ... .. ..  ...  ...  ...  ... ..  ...  ...  ...  ...   
389  1  20  2    2    1    2  2  0    1    1  ...    5  5    4    4    5    4   
390  1  17  3    1    2    1  0  0    0    0  ...    2  4    5    3    4    2   
391  1  21  1    1    1    1  3  0    0    0  ...    5  5    3    3    3    3   
392  1  18  3    2    3    1  0  0    0    0  ...    4  4    1    3    4    5   
393  1  19  1    1    1    1  0  0    0    0  ...    3  2    3    3    3    5   

      6   5  6.1  6.2  
0     4   5    5    6  
1    10   7    8   10  
2     2  15   14   15  
3     4   6   10   10  
4    10  15   15   15  
..   ..  ..  ...  ...  
389  11   9    9    9  
390   3  14   16   16  
391   3  10    8    7  
392   0  11   12   10  
393   5   8    9    9  

[394 rows x 25 columns]

In [158]:

input_layer_size  = 22

# 20 etiquetas, de 1 a 20 (tomar en cuenta que se asigna "0" a la etiqueta 21)
num_labels = 20
data = np.loadtxt('maths_pre.csv', delimiter=',')
X, y = data[:, 0:22], data[:, 22]
print(X)
print(y)

m = y.size

[[ 2. 18.  4. ...  1.  3.  6.]
 [ 2. 17.  1. ...  1.  3.  4.]
 [ 2. 15.  1. ...  3.  3. 10.]
 ...
 [ 1. 21.  1. ...  3.  3.  3.]
 [ 1. 18.  3. ...  4.  5.  0.]
 [ 1. 19.  1. ...  3.  5.  5.]]
[ 5.  5.  7. 15.  6. 15. 12.  6. 16. 14. 10. 10. 14. 10. 14. 14. 13.  8.
  6.  8. 13. 12. 15. 13. 10.  6. 12. 15. 11. 10.  9. 17. 17.  8. 12.  8.
 15. 15. 12. 14.  7. 12. 19.  8. 10.  8. 11. 19. 15.  7. 12. 11. 11.  8.
 10.  8. 14. 14.  9. 15. 10. 10.  8. 10. 10. 16. 13.  7.  8. 16. 13. 10.
  8. 12. 11.  9. 11. 11.  8.  5. 10. 11.  7. 15.  9.  7.  8. 13. 11.  8.
  7. 16.  7. 11. 11.  7. 11.  8. 11.  7.  7. 16. 10.  7. 16. 10.  7. 16.
 10. 14. 18.  7. 10. 18.  9. 15. 11. 13.  9. 14. 16. 16. 13. 14.  8. 13.
  7.  7.  7. 18. 12.  8. 10. 12.  9. 11. 10.  4. 14. 16.  7.  9.  9. 14.
  5.  8.  6. 10.  7.  8.  6. 12. 10.  5. 11. 11. 16.  9. 17. 10.  7.  5.
  7. 10.  5. 12. 10. 14.  6. 14.  6. 13. 13.  8. 10. 10. 13.  6. 10. 10.
  9. 12. 16.  9. 12. 12. 11. 15.  8.  8. 11.  8.  7.  8. 13. 14. 17.  9.
 18. 

In [159]:
print(X.shape)
print(y.shape)

(395, 22)
(395,)


In [160]:
# funcion para la normalizacion de caracteristicas
def  featureNormalize(X):
    X_norm = X.copy()
    media_norm = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    media_norm = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - media_norm) / sigma
    
    return X_norm, media_norm, sigma

In [161]:
X_norm, media_norm, sigma = featureNormalize(X)

In [162]:
X = X_norm
# X = X_datos
print(X[0])

[ 0.94817639  1.02304645  1.14385567  1.36037064  0.79225076 -0.04228585
 -0.44994364  2.59713266 -1.25765629 -0.91967081 -1.01788137  0.50789938
  0.23094011 -2.23267743 -0.70844982  0.06219406 -0.2360102   0.8014793
 -0.54069866 -1.00378921 -0.39928949  0.03642446]


In [163]:
def sigmoid(z):
    """
    Calcula la sigmoide de z.
    """
    return 1.0 / (1.0 + np.exp(-z))

In [164]:

h = sigmoid(75)
print(h)

1.0


In [165]:
def lrCostFunction(theta, X, y, lambda_):
    # Inicializa algunos valores utiles
    m = y.size
    # print(m)
    # convierte las etiquetas a valores enteros si son boleanos
    if y.dtype == bool:
        y = y.astype(int)
    
    J = 0
    grad = np.zeros(theta.shape)
    
    h = sigmoid(X.dot(theta.T))
    
    temp = theta
    temp[0] = 0
    
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h))) + (lambda_ / (2 * m)) * np.sum(np.square(temp))
    
    grad = (1 / m) * (h - y).dot(X) 
    grad = grad + (lambda_ / m) * temp

    return J, grad

In [166]:
def oneVsAll(X, y, num_labels, lambda_):
    # algunas variables utiles
    m, n = X.shape
    
    all_theta = np.zeros((num_labels, n + 1))

    # Agrega unos a la matriz X
    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    for c in np.arange(num_labels):
        initial_theta = np.zeros(n + 1)
        options = {'maxiter': 50}
        res = optimize.minimize(lrCostFunction, 
                                initial_theta, 
                                (X, (y == c), lambda_), 
                                jac=True, 
                                method='CG',
                                options=options) 
        
        all_theta[c] = res.x

    return all_theta

In [185]:
lambda_ = 0.1
all_theta = oneVsAll(X, y, num_labels, lambda_)
print(all_theta.shape)

(20, 23)


In [186]:
def predictOneVsAll(all_theta, X):
    m = X.shape[0];
    num_labels = all_theta.shape[0]

    p = np.zeros(m)

    # Add ones to the X data matrix
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    p = np.argmax(sigmoid(X.dot(all_theta.T)), axis = 1)

    return p

In [192]:
print(X.shape)
pred = predictOneVsAll(all_theta, X)
print('Precision del conjuto de entrenamiento: {:.2f}%'.format(np.mean(pred == y) * 100))
XPrueba = X[393:394, :].copy()
print(XPrueba.shape)

XPrueba = np.concatenate([np.ones((1, 1)), XPrueba], axis=1)
print(XPrueba.shape)
p = np.argmax(sigmoid(XPrueba.dot(all_theta.T)), axis = 1)
print('Nota examen: ',p)
print('valor esperado de examen', y[393])

(395, 22)
Precision del conjuto de entrenamiento: 32.66%
(1, 22)
(1, 23)
Nota examen:  [13]
valor esperado de examen 11.0
